spring:
  security:
    filter:
      order: 1
    user:
      password: 12345
    admin:
      password: admin
  application:
    name: ecommerce-be
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: dsavc3
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always

logging:
  level:
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    org:
      hibernate: debug
    web: DEBUG